### ISSUE TITLE
False-positive if name resolving isn't working

### ISSUE THREAD

**Issue by hrvylein** [meganukebmp/Switch_90DNS_tester#3]
Hey,

while using switch-lan-play i stumbled upon the issue i described here: https://github.com/spacemeowx2/switch-lan-play/issues/114

spacemeowx2 found the corresponding place in your code. Your code is working correctyl as dns resolving isn't returning 127.0.0.1 as the ip, but as the gateway is not working, internet access is blocked at all.

Maybe change the message to a yellowish color with message "unblocked (not resolved)" or sth similiar?

**Comment by meganukebmp** [comment]
Sorry for late reply. Confirmed. It also returns unblocked when the connection is off completely (wifi off). I'll add the corresponding checks asap. Thanks!

**Comment by meganukebmp** [comment]
Thanks for reporting. This issue has been resolved!
