### ISSUE TITLE
[Suggestion] Add an icon ?

### ISSUE THREAD

**Issue by Draky50110** [meganukebmp/Switch_90DNS_tester#4]
Hello.
Nice homebrew :)

Small suggestion : what about adding an icon ?
There is one in HBStore but not sure if it is an official one : https://apps.fortheusers.org/search/90dns

**Comment by meganukebmp** [comment]
It's a simple homebrew, so I havent really thought much about it. I guess an icon couldnt hurt. Do you wish to propose one? Or should I make something myself

**Comment by DraconicNEO** [comment]
> It's a simple homebrew, so I havent really thought much about it. I guess an icon couldnt hurt. Do you wish to propose one? Or should I make something myself

hey I know this is kind of Late but I decided to put together some proposal icons for this Homebrew, please let me know which one you like best or if I should make a new one in a different style.

I kept them at high resolution so you can downscale them however you feel like:

![90DNS Icon Proposal #1](https://user-images.githubusercontent.com/44508470/188577007-af04d864-544e-49c4-bfb8-0f88afae6892.png)
Icon Proposal 1

![90DNS Icon Proposal #2](https://user-images.githubusercontent.com/44508470/188577125-8f12c4b2-97b8-436b-ba39-35c0513639ad.png)
Icon Proposal 2

**Comment by meganukebmp** [comment]
Closed by 756c961329dd0cbaaba6445365d3922175ec885c
