### ISSUE TITLE
[Suggestion] Add a domain that shouldn't be blocked to the test

### ISSUE THREAD

**Issue by ghost** [meganukebmp/Switch_90DNS_tester#6]
Hello.

Small suggestion : what about adding, for example, Google, to the test? This way you could be more certain your network is working properly, running the test when offline gives the same result as successfully blocking the correct domains.

**Comment by DraconicNEO** [comment]
Addressed in pull request #8

**Comment by meganukebmp** [comment]
>  running the test when offline gives the same result as successfully blocking the correct domains.

Is this not ultimately true? Offline means no connection. I've added a warning that there is no network with 23d2cf64908fa1728130c242444b0c2daf3b8908.
I believe this should be sufficient. Adding unrelated to nintendo domains also means that logic should be updated to show such entries as green, since having them unlocked is not a negative. As a simple testing program I want it to be clear when a block is a full block and when it is not. All greens = OK. Red and yellow = Caution.

I'll close this as resolved with 23d2cf64908fa1728130c242444b0c2daf3b8908. Feel free to reopen if you'd propose something else.

**Comment by DraconicNEO** [comment]
> > running the test when offline gives the same result as successfully blocking the correct domains.
> 
> Is this not ultimately true? Offline means no connection. I've added a warning that there is no network with [23d2cf6](https://github.com/meganukebmp/Switch_90DNS_tester/commit/23d2cf64908fa1728130c242444b0c2daf3b8908). I believe this should be sufficient. Adding unrelated to nintendo domains also means that logic should be updated to show such entries as green, since having them unlocked is not a negative. As a simple testing program I want it to be clear when a block is a full block and when it is not. All greens = OK. Red and yellow = Caution.
> 
> I'll close this as resolved with [23d2cf6](https://github.com/meganukebmp/Switch_90DNS_tester/commit/23d2cf64908fa1728130c242444b0c2daf3b8908). Feel free to reopen if you'd propose something else.

I was thinking that including some domains that shouldn't be blocked that are used by Homebrew would be a good idea since it could show network problems that aren't necessarily related to just not having Wi-Fi or Flight Mode turned on.

**Comment by meganukebmp** [comment]
> I was thinking that including some domains that shouldn't be blocked that are used by Homebrew would be a good idea since it could show network problems that aren't necessarily related to just not having Wi-Fi or Flight Mode turned on.

This tool only does DNS resolution checks. It doesn't check if a host is reachable or even if it exists. All it does is ask the DNS server what a domain maps to. It cannot show further network issues other than DNS misconfiguration. In the context of of blocking Nintendo domains this means whether or not they are redirected to localhost. Localhost = green, everything else = not green. I think it's sufficient and compact enough for what it does.
